# -*- coding: utf-8 -*-
"""scraping_data.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FPFhkW2UjTfsW8vV5nU_ncVeMZfVaF9G

**SCRAPING DATA ULASAN TOKOPEDIA APP UNTUK ANALISIS SENTIMEN NLP**

Menggunakan google-play-scraper

Output: dataset_scraping.csv

**1. Install Library**
"""

!pip install google-play-scraper pandas

"""**2. Scraping dari Google Play Store Reviews**"""

from google_play_scraper import reviews
import pandas as pd

app_id = "com.tokopedia.tkpd"   # menggunakan aplikasi tokopedia
count = 13000                  # target >10.000

result, _ = reviews(
    app_id,
    lang='id',
    country='id',
    count=count
)

texts = [r['content'] for r in result]

df = pd.DataFrame(texts, columns=['text'])
df.drop_duplicates(inplace=True)
df.dropna(inplace=True)

df.to_csv("dataset_scraping.csv", index=False, encoding="utf-8")

print("Scraping selesai")
print("Jumlah data:", len(df))